export const REPOSITORIES = {
    CATEGORY: 'CATEGORY_REPOSITORY',
    CUSTOMER: 'CUSTOMER_REPOSITORY',
    INVOICE: 'INVOICE_REPOSITORY',
    INVOICE_DETAIL: 'INVOICEDETAIL_REPOSITORY',
    INVENTORY_MOVEMENT: 'INVENTORYMOVEMENT_REPOSITORY',
    PRODUCT: 'PRODUCT_REPOSITORY',
    ROLE: 'ROLE_REPOSITORY',
    SUPPLIER: 'SUPPLIER_REPOSITORY',
    USER: 'USER_REPOSITORY',
};

export const DATA_SOURCE = 'DATA_SOURCE';
